name: TrustBench Eval Suite

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pytest pyyaml
      - name: Run Evaluation
        run: |
          python -c "import sys; from eval.evaluate_agent import main; main()"
      - name: Build Report
        run: |
          python -c "from eval.report import main as rpt; rpt()"
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: trustbench-eval-report
          path: reports/last_report.md
