# .github/workflows/agent-eval.yml
name: Agent Evaluation

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pytest pyyaml
          # later: pip install ragas deepeval sentence-transformers httpx
      - name: Run evaluation
        run: |
          python eval/evaluate_agent.py
