name: TrustBench Evaluation
on: [pull_request]
jobs:
  eval:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
  GROQ_MODEL: llama-3.3-70b-versatile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -e .[dev]
      - run: python -m trustbench_core.orchestrator --profile profiles/default.yaml --ci
      - uses: actions/upload-artifact@v4
        with:
          name: trustbench-artifacts
          path: runs/**
